./create-html-related-books.sh 11
./create-html-related-books.sh 12
./create-html-related-books.sh 13
./create-html-related-books.sh 14
./create-html-related-books.sh 15
./create-html-related-books.sh 16
./create-html-related-books.sh 17
./create-html-related-books.sh 18
./create-html-related-books.sh 19
./create-html-related-books.sh 110
./create-html-related-books.sh 21
./create-html-related-books.sh 22
./create-html-related-books.sh 23
./create-html-related-books.sh 24
./create-html-related-books.sh 25
./create-html-related-books.sh 26
./create-html-related-books.sh 27
./create-html-related-books.sh 28
./create-html-related-books.sh 29
./create-html-related-books.sh 210
./create-html-related-books.sh 31
./create-html-related-books.sh 32
./create-html-related-books.sh 33
./create-html-related-books.sh 34
./create-html-related-books.sh 35
./create-html-related-books.sh 36
./create-html-related-books.sh 37
./create-html-related-books.sh 38
./create-html-related-books.sh 39
./create-html-related-books.sh 310
./create-html-related-books.sh 41
./create-html-related-books.sh 42
./create-html-related-books.sh 43
./create-html-related-books.sh 44
./create-html-related-books.sh 45
./create-html-related-books.sh 46
./create-html-related-books.sh 47
./create-html-related-books.sh 48
./create-html-related-books.sh 49
./create-html-related-books.sh 410
./create-html-related-books.sh 51
./create-html-related-books.sh 52
./create-html-related-books.sh 53
./create-html-related-books.sh 54
./create-html-related-books.sh 55
./create-html-related-books.sh 56
./create-html-related-books.sh 57
./create-html-related-books.sh 58
./create-html-related-books.sh 59
./create-html-related-books.sh 510
./create-html-related-books.sh 61
./create-html-related-books.sh 62
./create-html-related-books.sh 63
./create-html-related-books.sh 64
./create-html-related-books.sh 65
./create-html-related-books.sh 66
./create-html-related-books.sh 67
./create-html-related-books.sh 68
./create-html-related-books.sh 69
./create-html-related-books.sh 610
./create-html-related-books.sh 71
./create-html-related-books.sh 72
./create-html-related-books.sh 73
./create-html-related-books.sh 74
./create-html-related-books.sh 75
./create-html-related-books.sh 76
./create-html-related-books.sh 77
./create-html-related-books.sh 78
./create-html-related-books.sh 79
./create-html-related-books.sh 710
##
mv books-matrix-1.* books-matrix-2.* books-matrix-3.* books-matrix-4.* books-matrix-5.* books-matrix-6.* books-matrix-7.* ../photos/books/.
